---
agimus_controller_node:
  ros__parameters:
    rate: 100.0
    ocp:
      dt: 0.01
      horizon_size: 20
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      gripper_weight: 500.0
      state_weight: 5.0
      control_weight: 0.001
      max_qp_iter: 100
      max_iter: 10
      use_constraints: true
      activate_callback: false
      increasing_weights:
        max: 100.0
        percent: 0.9
        time_reach_percent: 6
      effector_frame_name: fer_link8

