---
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    gripper_action_controller:
      type: effort_controllers/GripperActionController


gripper_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    # For now hardcoded. To be fixed later
    joint: "fer_finger_joint1"
    gains.fer_finger_joint1:
      d: 10.0
      i: 0.0
      i_clamp: 0.0
      p: 10.0
