linear_feedback_controller:
  ros__parameters:
    moving_joint_names: [
      'fer_joint_1',
      'fer_joint_2',
      'fer_joint_3',
      'fer_joint_4',
      'fer_joint_5',
      'fer_joint_6',
      'fer_joint_7'
    ]
    fer_joint_1:
      p: 0.0
      d: 0.0
    fer_joint_2:
      p: 0.0
      d: 0.0
    fer_joint_3:
      p: 0.0
      d: 0.0
    fer_joint_4:
      p: 0.0
      d: 0.0
    fer_joint_5:
      p: 0.0
      d: 0.0
    fer_joint_6:
      p: 0.0
      d: 0.0
    fer_joint_7:
      p: 0.0
      d: 0.0
    chainable_controller:
      command_prefix: 'fer_'
      reference_prefix: ''
    joint_velocity_filter_coefficient: 0.9
    pd_to_lf_transition_duration: '0.1'
    remove_gravity_compensation_effort: 'true'
    robot_has_free_flyer: 'false'